"""Created products

Revision ID: bf9ab3f3ab73
Revises: 621337e4bcd7
Create Date: 2022-12-22 12:00:21.121045

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf9ab3f3ab73"
down_revision = "621337e4bcd7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("product_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("product_no"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
