"""Added phone table

Revision ID: 621337e4bcd7
Revises: 4da06cae3a24
Create Date: 2022-12-02 13:26:35.258426

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "621337e4bcd7"
down_revision = "5e38e5884329"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pnone", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("phone_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "phone_id")
    op.drop_table("phone")
    # ### end Alembic commands ###
