"""Created products 

Revision ID: bf9ab3f3ab72
Revises: 621337e4bcd7
Create Date: 2022-12-22 12:00:21.121045

"""
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, func



# revision identifiers, used by Alembic.
revision = 'bf9ab3f3ab72'
down_revision = '1f8a9d811105'
branch_labels = 'versions_constraint_check_invalid'
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'products',
        sa.Column('product_no', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('price', sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint('product_no'),
        
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
